/// Common suggestions for autocomplete fields
class Suggestions {
  // Pizza cheeses - common varieties used in pizza making
  static const List<String> cheeses = [
    'Mozzarella',
    'Fresh Mozzarella',
    'Burrata',
    'Parmesan',
    'Pecorino Romano',
    'Provolone',
    'Ricotta',
    'Gorgonzola',
    'Fior di Latte'
    'Fontina',
    'Goat Cheese',
    'Feta',
    'Cheddar',
    'Gruyère',
    'Asiago',
    'Mascarpone',
    'Blue Cheese',
    'Brie',
    'Gouda',
    'Taleggio',
    'Stracciatella',
  ];

  // Pizza toppings - common pizza toppings
  static const List<String> toppings = [
    'Pepperoni',
    'Italian Sausage',
    'Mushrooms',
    'Onions',
    'Red Onions',
    'Bell Peppers',
    'Olives',
    'Black Olives',
    'Kalamata Olives',
    'Jalapeños',
    'Anchovies',
    'Bacon',
    'Ham',
    'Prosciutto',
    'Salami',
    'Soppressata',
    'Capicola',
    'Nduja',
    'Fresh Basil',
    'Arugula',
    'Spinach',
    'Sun-dried Tomatoes',
    'Roasted Garlic',
    'Caramelized Onions',
    'Artichoke Hearts',
    'Roasted Red Peppers',
    'Cherry Tomatoes',
    'Pineapple',
    'Banana Peppers',
    'Hot Honey',
    'Potato',
    'Truffles',
    'Eggplant',
    'Zucchini',
    'Broccoli',
    'Kale',
    'Fresh Tomato',
    'Corn',
    'Chicken',
    'Ground Beef',
    'Shrimp',
    'Clams',
    'Egg',
  ];

  // Common ingredient preparations/descriptions
  static const List<String> preparations = [
    'diced',
    'minced',
    'chopped',
    'sliced',
    'julienned',
    'cubed',
    'grated',
    'shredded',
    'crushed',
    'ground',
    'melted',
    'softened',
    'room temperature',
    'cold',
    'frozen',
    'thawed',
    'fresh',
    'dried',
    'canned',
    'drained',
    'rinsed',
    'peeled',
    'seeded',
    'deveined',
    'trimmed',
    'halved',
    'quartered',
    'thinly sliced',
    'roughly chopped',
    'finely diced',
    'finely minced',
    'coarsely chopped',
    'to taste',
    'divided',
    'packed',
    'sifted',
    'toasted',
    'blanched',
    'roasted',
    'grilled',
    'smoked',
    'cured',
    'marinated',
    'brined',
  ];

  // Wood types for smoking recipes
  static const List<String> woodTypes = [
    'Hickory',
    'Mesquite',
    'Apple',
    'Cherry',
    'Oak',
    'Pecan',
    'Maple',
    'Alder',
    'Peach',
    'Pear',
    'Walnut',
    'Apricot',
    'Plum',
    'Mulberry',
    'Orange',
    'Lemon',
    'Grapevine',
    'Bourbon Barrel',
    'Wine Barrel',
    'Post Oak',
    'White Oak',
    'Red Oak',
  ];

  // Common seasonings for smoking
  static const List<String> seasonings = [
    'Kosher Salt',
    'Black Pepper',
    'Garlic Powder',
    'Onion Powder',
    'Paprika',
    'Smoked Paprika',
    'Cayenne',
    'Chili Powder',
    'Cumin',
    'Brown Sugar',
    'Mustard Powder',
    'Celery Salt',
    'Coriander',
    'Oregano',
    'Thyme',
    'Rosemary',
    'Sage',
    'Bay Leaves',
    'Coffee',
    'Cocoa Powder',
  ];

  /// Filter suggestions based on query
  static List<String> filter(List<String> suggestions, String query) {
    if (query.isEmpty) return suggestions;
    final lower = query.toLowerCase();
    return suggestions
        .where((s) => s.toLowerCase().contains(lower))
        .toList();
  }
}
