/// Common suggestions for autocomplete fields
class Suggestions {
  // Pizza cheeses - common varieties used in pizza making
  static const List<String> cheeses = [
    'Mozzarella',
    'Fresh Mozzarella',
    'Burrata',
    'Parmesan',
    'Pecorino Romano',
    'Provolone',
    'Ricotta',
    'Gorgonzola',
    'Fior di Latte'
    'Fontina',
    'Goat Cheese',
    'Feta',
    'Cheddar',
    'Gruyère',
    'Asiago',
    'Mascarpone',
    'Blue Cheese',
    'Brie',
    'Gouda',
    'Taleggio',
    'Stracciatella',
  ];

  // Pizza toppings - common pizza toppings
  static const List<String> toppings = [
    'Pepperoni',
    'Italian Sausage',
    'Mushrooms',
    'Onions',
    'Red Onions',
    'Bell Peppers',
    'Olives',
    'Black Olives',
    'Kalamata Olives',
    'Jalapeños',
    'Anchovies',
    'Bacon',
    'Ham',
    'Prosciutto',
    'Salami',
    'Soppressata',
    'Capicola',
    'Nduja',
    'Fresh Basil',
    'Arugula',
    'Spinach',
    'Sun-dried Tomatoes',
    'Roasted Garlic',
    'Caramelized Onions',
    'Artichoke Hearts',
    'Roasted Red Peppers',
    'Cherry Tomatoes',
    'Pineapple',
    'Banana Peppers',
    'Hot Honey',
    'Potato',
    'Truffles',
    'Eggplant',
    'Zucchini',
    'Broccoli',
    'Kale',
    'Fresh Tomato',
    'Corn',
    'Chicken',
    'Ground Beef',
    'Shrimp',
    'Clams',
    'Egg',
  ];

  // Common ingredient preparations/descriptions
  static const List<String> preparations = [
    'diced',
    'minced',
    'chopped',
    'sliced',
    'julienned',
    'cubed',
    'grated',
    'shredded',
    'crushed',
    'ground',
    'melted',
    'softened',
    'room temperature',
    'cold',
    'frozen',
    'thawed',
    'fresh',
    'dried',
    'canned',
    'drained',
    'rinsed',
    'peeled',
    'seeded',
    'deveined',
    'trimmed',
    'halved',
    'quartered',
    'thinly sliced',
    'roughly chopped',
    'finely diced',
    'finely minced',
    'coarsely chopped',
    'to taste',
    'divided',
    'packed',
    'sifted',
    'toasted',
    'blanched',
    'roasted',
    'grilled',
    'smoked',
    'cured',
    'marinated',
    'brined',
  ];

  // Wood types for smoking recipes
  static const List<String> woodTypes = [
    'Hickory',
    'Mesquite',
    'Apple',
    'Cherry',
    'Oak',
    'Pecan',
    'Maple',
    'Alder',
    'Peach',
    'Pear',
    'Walnut',
    'Apricot',
    'Plum',
    'Mulberry',
    'Orange',
    'Lemon',
    'Grapevine',
    'Bourbon Barrel',
    'Wine Barrel',
    'Post Oak',
    'White Oak',
    'Red Oak',
  ];

  // Common seasonings for smoking
  static const List<String> seasonings = [
    'Kosher Salt',
    'Black Pepper',
    'Garlic Powder',
    'Onion Powder',
    'Paprika',
    'Smoked Paprika',
    'Cayenne',
    'Chili Powder',
    'Cumin',
    'Brown Sugar',
    'Mustard Powder',
    'Celery Salt',
    'Coriander',
    'Oregano',
    'Thyme',
    'Rosemary',
    'Sage',
    'Bay Leaves',
    'Coffee',
    'Cocoa Powder',
  ];

  // Sandwich bread types
  static const List<String> breads = [
    'Sourdough',
    'Ciabatta',
    'Baguette',
    'Hoagie Roll',
    'French Bread',
    'Brioche',
    'Rye',
    'Pumpernickel',
    'Focaccia',
    'Pita',
    'Naan',
    'Tortilla',
    'White Bread',
    'Wheat Bread',
    'Multigrain',
    'Kaiser Roll',
    'Croissant',
    'English Muffin',
    'Bagel',
    'Cuban Bread',
    'Italian Bread',
    'Pretzel Bun',
    'Challah',
    'Texas Toast',
  ];

  // Sandwich proteins
  static const List<String> proteins = [
    'Turkey',
    'Ham',
    'Roast Beef',
    'Chicken Breast',
    'Blackened Chicken',
    'Grilled Chicken',
    'Fried Chicken',
    'Bacon',
    'Pastrami',
    'Corned Beef',
    'Salami',
    'Pepperoni',
    'Prosciutto',
    'Capicola',
    'Mortadella',
    'Bologna',
    'Pulled Pork',
    'Carnitas',
    'Brisket',
    'Meatballs',
    'Sausage',
    'Chorizo',
    'Tuna Salad',
    'Egg Salad',
    'Chicken Salad',
    'Shrimp',
    'Crab',
    'Lobster',
    'Fried Egg',
    'Tofu',
    'Tempeh',
    'Falafel',
  ];

  // Sandwich vegetables
  static const List<String> vegetables = [
    'Lettuce',
    'Romaine',
    'Arugula',
    'Spinach',
    'Tomato',
    'Red Onion',
    'White Onion',
    'Pickled Onion',
    'Caramelized Onion',
    'Pickles',
    'Dill Pickles',
    'Bread & Butter Pickles',
    'Cucumber',
    'Bell Pepper',
    'Roasted Red Pepper',
    'Jalapeño',
    'Banana Peppers',
    'Hot Peppers',
    'Avocado',
    'Sprouts',
    'Microgreens',
    'Coleslaw',
    'Sauerkraut',
    'Kimchi',
    'Olives',
    'Artichoke Hearts',
    'Sun-dried Tomatoes',
    'Mushrooms',
    'Grilled Zucchini',
    'Eggplant',
    'Roasted Garlic',
  ];

  // Sandwich condiments
  static const List<String> condiments = [
    'Mayonnaise',
    'Spicy Mayo',
    'Chipotle Mayo',
    'Garlic Aioli',
    'Mustard',
    'Yellow Mustard',
    'Dijon Mustard',
    'Honey Mustard',
    'Whole Grain Mustard',
    'Ketchup',
    'BBQ Sauce',
    'Hot Sauce',
    'Sriracha',
    'Buffalo Sauce',
    'Ranch',
    'Italian Dressing',
    'Balsamic Vinaigrette',
    'Olive Oil',
    'Pesto',
    'Hummus',
    'Tzatziki',
    'Horseradish',
    'Remoulade',
    'Thousand Island',
    'Russian Dressing',
    'Caesar Dressing',
    'Guacamole',
    'Salsa',
    'Chimichurri',
    'Butter',
    'Cream Cheese',
  ];

  /// Filter suggestions based on query
  static List<String> filter(List<String> suggestions, String query) {
    if (query.isEmpty) return suggestions;
    final lower = query.toLowerCase();
    return suggestions
        .where((s) => s.toLowerCase().contains(lower))
        .toList();
  }
}
